---
name: Manage stale PRs
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: |
            This PR is stale because it has been for over 15 days with no activity.
            Remove stale label or comment or this PR will be closed in 7 days.
          days-before-pr-stale: 15
          days-before-pr-close: 7
